export default {
    "baseBorderRadius": "0",
    "baseFontFamily":  '"Open Sans",Arial,sans-serif',
    "favFontFamily": '"georgia", "serif"',
    "alternateFontFamily": "Verdana, sans-serif",
    "h1_size": "24px",
    "h2_size": "18px",
    "h3_size": "16px",
    "h4_size": "14px",
    "h5_size": "12px",
    "h6_size": "11px",   
    "S": "320px",  
    "M": "768px",    
    "L": "1024px",  
    "XL": "1400px",   
    "h12_size": "20px",
    "gaint_size": "28px",
    "top_heading_height": "70px",
    "text_weight_thin": "300",
    "text_weight_regular": "400",
    "text_weight_thick": "600",
    "text_weight_thickest": "700",
    "message_default" : "#cc3a3e",
    "message_error" : "#CC3333",
    "message_error2" : "#D0021B",
    "message_warning" : "#FF9966",
    "message_success" : "#00CC99",
    "text_color_faint": "#b1b1b1",
    "text_color_light2": "#666",
    "text_color_light":  "#567181",
    "text_color_bbb": "#bbb",
    "text_color_999": "#999",
    "text_color_dark": "#222",
    "text_color_black": "#000",
    "text_color_blue": "#6fc5e8",
    "text_color_blue_dashboard": "#afdafe",
    "text_color_dark_orange": "#562111",
    "text_color_tour_heading": "#299fdd",
    "text_dark_yellow_color": "#7B7A67",
    "text_color_anchor_blue": "#2daaec",
    "text_color_anchor_red": "#fa3a2d",
    "text_color_anchor_dark_red": "#db1725",   
    "activity_bar_min_width": "1260px",
    "activity_bar_max_width": "1259px",   
    "theme_white" : "#FFF",
    "lsb_bg": "#27353e",
    "lsb_active_bg": "#191919",
    "anchor_color": "#00aced",
    "theme_red_color": "#e62226",
    "theme_blue_color": "#1d90d6",
    "dropdown_bg_blue": "#31414a",
    "dropdown_border": "#1b282f",
    "header_light_border": "#DEE8EF",//#eaeef1
    "header_lightest_border": "#eaeef1",
    "blue_border": "#618fb5",
    "header_dark_border": "#ced6dc",
    "header_text_color": "#567181",
    "yellow_bg": "#ffffcc",
    "body_bg": " #f2f4f8",
    "toolbar_bg": "#f9fafc",
    "head_tab_bg": "#e7e9ed",
    "blue_btn_bg": "#018dec",
    "blue_btn_hover_bg": "#00b8fd",
    "calendar_selection": "#8ff139",
    "disabled_input_bg": "#E7EDF2",
    "modal_bg": "#E7EDF2",
    "lsb_width": "70px",
    "header_height": "76px",
    "insight_height": "216px",
    "new_modal_bg" : "#F2F4F8",
    "new_body_bg" : "#E7EDF2",
    "bottom_header_height": "48px",
    "nouislider_color" : "#e7e9ed",
    "signup_text_color" : "#304149",
    "link_hover_color" :  "#1d90d6",
    "signup_text_light_color" : "#babdbf",
    "theme_dark_second_color" : "#27353e",
    "theme_light_dark_color" : "#F3F6FC",
    "signup_error_color" : "#ff2300",
    "signup_success_color" : "#00c60f",
    "signup_button_hover" : "#099bfe",
    "theme_dark_color" : "#1c2731",
    "theme_dark_color2" : "#31414a",
    "theme_light_color2" : "#F4F7FC",
    "theme_gray_color" : "#DEE8EF",
    "leftbar_settings_bg" : "#1c2731",
    "leftbar_settings_link" : "#567181",
    "setup_progress_color" : "#d4d4d4",
    "theme_new_blue_color" : "#018dec",
    "body_bg_new" : "#f5f9fb",
    "button_secondary_bg" : "#dcf0fc",
    "table_head_bg" : "#637987",
    "table_head_color" : "#fbfbfb",
    "text_light_new_color" : "#5b6971",
    "funnel_primary_text_color" : "#e6f1f5",
    "theme_light_color" : "#A5C0D6",
    "table_even_bg" : "#F3F6FC",
    "input_border_color" : "#DEE8EF",
    "input_dark_bg" : "#F9FAFC",
    "warning_color" : "#F9FED8",
    "yellow_color" : "#CFCA47",
    "theme_skyblue_color" : "#DDF1FD",
    "dotted_border_color" : "#637A89",
    "yellow_border_color" : "#E8EEC0",
    "theme_dark_blue" : "#0075A2",
    "green_color" : "#8cc152",
    "button_disabled" : "#cec3c3",
    "button_red_color" : "#ed5565",
    "example_color": "#9FBBD3",
    "z" : "test"
}


